### ISSUE TITLE
[ROADMAP] Magento 2 - VueStorefront 2

### ISSUE THREAD

**Issue by bloodf** [vuestorefront/magento2#75]
This is an early-stage roadmap with some of the features that are needed, to have a complete store running and be able to be production-ready.

--------------

### Product

- [x] Display Customizable Product #22
- [x] Configure a Customizable Product to be able to add to cart #22
- [ ] Access a Customizable Product URL with options, and those settings get applied #22
- [x] Add Product Review #86 
- [x] Display product attributes and extra information #22

### Category

- [x] Display the filter sidebar #20 #99 

### User

- [x] Create the Wishlist Process #102
- [x] Manage Newletters on Magento #93

#### External Checkout

- [x] Create the external checkout process
- [x] ThankYou page #24
- [ ] Create the external checkout Magento 2 Plugin 

#### Internal Checkout

- [x] Create the internal checkout process #24
- [x] Develop the checkout process for Guest User #24
- [x] Develop the checkout process for Authenticated User #24
- [x] ThankYou page #24
- [x] Coupon and Discount codes process #24

**Comment by Frodigo** [comment]
Hey @bloodf, this looks promising! I just want to friendly ask Is the approximate date when the integration will be production-ready is known?

**Comment by bloodf** [comment]
Thanks @Frodigo, but for now I can't provide any ETA :(
